### PR TITLE
Python3 support.

### LINKED ISSUE #10: No module named 'urllib2'
hi
am on OSX and getting the following error:
----
  File "extract_occurrences.py", line 5, in <module>
    from urllib2 import Request, build_opener, HTTPCookieProcessor
ModuleNotFoundError: No module named 'urllib2'
-------
thx

### PR DESCRIPTION
**Pull request by muammar**
This commit adds python3 support. Closes #10.

### CODE REVIEW

**Comment by Pold87** [comment]
Thank you for the pull request. However, have you seen the Python 3 branch? I think it already includes the changes you made in this commit.

**Comment by muammar** [comment]
> Thank you for the pull request. However, have you seen the Python 3 branch? I think it already includes the changes you made in this commit.

No, I did not. Why are not those changes already included in master? Python2 should be dead by next year. Feel free to close this PR.

**Comment by Pold87** [comment]
That's a good point, I'll include the changes in master and keep a Python 2
branch.

**Comment by muammar** [comment]
Nice, thanks for being so responsive :).

**Comment by Pold87** [comment]
No problem, it's done now.

**Pull request closed without merging**
